SELECT 
CAST('123' AS INT) AS [STRING TO INT],
CAST(123 AS VARCHAR) AS [INT TO STRING],
CAST('2025-08-20' AS DATE) AS [STRING TO DATE],
CAST('2025-08-20' AS DATETIME2) AS [STRING TO DATETIME],
CreationTime,
CAST(CreationTime AS DATE) AS [DATETIME2 TO DATE]
FROM Sales.Orders
